from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import httpx
from pydantic import BaseModel
import sqlite3

# --- SETUP UNIVERSITY DATABASE ---
# This creates a local file named 'university.db' in your backend folder
db_conn = sqlite3.connect('university.db', check_same_thread=False)
cursor = db_conn.cursor()

# Create a table where student_id is the UNIQUE PRIMARY KEY
cursor.execute('''
    CREATE TABLE IF NOT EXISTS issued_credentials (
        student_id TEXT PRIMARY KEY,
        student_name TEXT,
        email TEXT,
        exchange_id TEXT
    )
''')
db_conn.commit()
# --- CONFIGURATION ---
ACAPY_ADMIN_URL = "http://127.0.0.1:8020"

# Schema & Credential Definition IDs generated by setup_schemas.py
STUDENT_SCHEMA_ID = "GEX6Tv3ywc7HzWukCyveY5:2:student_id_credential:1.8031"
STUDENT_CRED_DEF_ID = "GEX6Tv3ywc7HzWukCyveY5:3:CL:3224602:brac_tag_8031"
app= FastAPI()

# --- PYDANTIC REQUEST MODELS ---
class RegisterRequest(BaseModel):
  gov_id: str
  name: str


class IssueCredentialRequest(BaseModel):
  connection_id: str
  student_name: str
  student_id: str
  department: str
  email: str
class VerifyRequest(BaseModel):
    connection_id: str

# --- APPLICATION SETUP ---
app = FastAPI(
    title="BRAC University SSI Portal Backend",
    description="ACA-Py Bridge for Student ID Issuance and Verification",
    version="1.0.0",
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows all origins for local testing
    allow_credentials=True,
    allow_methods=["*"],  # Allows all methods (GET, POST, etc.)
    allow_headers=["*"],  # Allows all headers
)

# --- ROUTES ---


@app.get("/")
def health_check():
  """Basic health check endpoint to confirm backend availability."""
  return {
      "status": "active",
      "mode": "ACA-Py SSI Bridge",
      "acapy_url": ACAPY_ADMIN_URL,
  }

@app.post("/protocol1/create-invitation")
async def create_invitation():
    """Generates a QR code invitation for the mobile wallet to scan."""
    async with httpx.AsyncClient() as client:
        try:
            # Tell ACA-Py to create a new connection invitation
            res = await client.post(
                f"{ACAPY_ADMIN_URL}/connections/create-invitation",
                params={"auto_accept": "true"}
            )
            res.raise_for_status()
            data = res.json()
            
            return {
                "status": "success",
                "connection_id": data["connection_id"],
                "invitation_url": data["invitation_url"]
            }
        except Exception as e:
            print(f"❌ Failed to create invitation: {e}")
            raise HTTPException(status_code=500, detail="Failed to create connection invitation")
          
          
@app.post("/protocol1/register")
async def create_ssi_identity(req: RegisterRequest):
  """Generates a new Ed25519 DID inside the ACA-Py wallet for local user registration.

  (M8 IPFS and M9 Ethereum Anchoring stripped).
  """
  print(
      f"\n--- 🆔 PROTOCOL 1: GENERATING SSI IDENTITY FOR {req.name.upper()} ---"
  )

  async with httpx.AsyncClient() as client:
    # 1. Verify ACA-Py Agent Availability
    try:
      health = await client.get(f"{ACAPY_ADMIN_URL}/status/ready")
      health.raise_for_status()
    except Exception:
      raise HTTPException(
          status_code=502,
          detail="ACA-Py Agent is unreachable. Check Docker container status.",
      )

    # 2. Create Ed25519 DID via ACA-Py
    try:
      response = await client.post(
          f"{ACAPY_ADMIN_URL}/wallet/did/create",
          json={"method": "sov", "options": {"key_type": "ed25519"}},
      )
      response.raise_for_status()

      data = response.json()["result"]
      ssi_did = data["did"]
      verkey = data["verkey"]

      print(f"   ↳ 🔐 Keypair Generated | DID: {ssi_did}")

      return {
          "status": "success",
          "ssi_did": ssi_did,
          "verkey": verkey,
          "gov_id": req.gov_id,
          "message": "Identity keypair successfully provisioned in wallet.",
      }

    except Exception as e:
      print(f"❌ DID Creation Failed: {e}")
      raise HTTPException(
          status_code=500, detail=f"Failed to generate DID: {str(e)}"
      )


@app.get("/protocol1/check-connection/{connection_id}")
async def check_connection(connection_id: str):
  """Polling endpoint used by Next.js frontend to verify if student has scanned the QR code with their mobile wallet (Bifold/BC Wallet)."""
  async with httpx.AsyncClient() as client:
    try:
      response = await client.get(
          f"{ACAPY_ADMIN_URL}/connections/{connection_id}"
      )
      if response.status_code == 404:
        raise HTTPException(status_code=404, detail="Connection ID not found")

      response.raise_for_status()
      data = response.json()
      state = data.get("state", "unknown")
      is_connected = state in ["active", "response"]

      return {
          "connection_id": connection_id,
          "state": state,
          "connected": is_connected,
      }

    except HTTPException:
      raise
    except Exception as e:
      raise HTTPException(status_code=500, detail=str(e))
    
    
    
@app.post("/protocol1/issue-credential")
async def issue_credential(req: IssueCredentialRequest):
    """Issues a Student ID credential directly to the connected mobile wallet."""
    print(f"\n--- 🚀 ISSUING STUDENT ID TO CONNECTION: {req.connection_id} ---")
    
    try:
        # 🚨 THE GATEKEEPER CHECK 🚨
        # 1. Check if this Student ID has already been issued
        cursor.execute("SELECT student_name FROM issued_credentials WHERE student_id = ?", (req.student_id,))
        existing_record = cursor.fetchone()
        
        if existing_record:
            print(f"⚠️ REJECTED: Credential already exists for ID {req.student_id} (Owned by {existing_record[0]})")
            raise HTTPException(
                status_code=400, 
                detail=f"A credential for Student ID {req.student_id} has already been issued to {existing_record[0]}."
            )

        # 2. Map the attributes
        aca_py_attributes = [
            {"name": "student_name", "value": req.student_name},
            {"name": "student_id", "value": req.student_id},
            {"name": "department", "value": req.department},
            {"name": "email", "value": req.email}
        ]

        # 3. Send the Credential Offer via ACA-Py
        async with httpx.AsyncClient() as client:
            aca_res = await client.post(
                f"{ACAPY_ADMIN_URL}/issue-credential-2.0/send",
                json={
                    "connection_id": req.connection_id,
                    "filter": {
                        "indy": {
                            "cred_def_id": STUDENT_CRED_DEF_ID,
                            "schema_id": STUDENT_SCHEMA_ID
                        }
                    },
                    "credential_preview": {
                        "@type": "issue-credential/2.0/credential-preview",
                        "attributes": aca_py_attributes
                    }
                },
                timeout=30.0
            )
            
            if aca_res.status_code != 200:
                raise HTTPException(status_code=aca_res.status_code, detail=f"ACA-Py error: {aca_res.text}")

            data = aca_res.json()
            exchange_id = data.get("cred_ex_id")
            
            # 🚨 SECURE THE ID 🚨
            # 4. Save the issued ID to the database so it can't be registered again
            cursor.execute(
                "INSERT INTO issued_credentials (student_id, student_name, email, exchange_id) VALUES (?, ?, ?, ?)",
                (req.student_id, req.student_name, req.email, exchange_id)
            )
            db_conn.commit()

            print(f"✅ Credential Offer Sent! ID {req.student_id} is now locked in the database.")

            return {
                "status": "success",
                "message": "Student ID Credential sent to mobile wallet.",
                "exchange_id": exchange_id
            }

    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ ISSUANCE FAILED: {e}")
        raise HTTPException(status_code=500, detail=str(e)) 




@app.post("/protocol2/connect-verifier")
async def connect_verifier():
    """Generates a QR code invitation for the login/verification step."""
    print("📡 Generating Verifier Connection Invitation...")
    async with httpx.AsyncClient() as client:
        try:
            body = {
                "alias": "BRACU Student",
                "my_label": "BRAC University Portal" # The phone will see this name!
            }
            response = await client.post(
                f"{ACAPY_ADMIN_URL}/connections/create-invitation", 
                json=body
            )
            
            if response.status_code != 200:
                raise HTTPException(status_code=500, detail=f"Agent Error: {response.text}")
                
            data = response.json()
            
            return {
                "status": "success",
                "connection_id": data["connection_id"],
                "invitation_url": data["invitation_url"],
                "message": "Scan this with BC Wallet to Log In"
            }
        except Exception as e:
            print(f"❌ Connection Error: {e}")
            raise HTTPException(status_code=500, detail=str(e))

@app.get("/protocol2/check-connection/{connection_id}")
async def check_verifier_connection(connection_id: str):
    """Allows the frontend to auto-detect when the user scans the login QR code."""
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(f"{ACAPY_ADMIN_URL}/connections/{connection_id}")
            state = response.json().get("state", "init")
            is_connected = state in ["active", "response"]
            return {"state": state, "connected": is_connected}
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))

@app.post("/protocol2/request-proof")
async def request_proof(req: VerifyRequest):
    """Requests proof of the BRACU Student ID credential."""
    print(f"\n--- 🕵️ PROTOCOL 2: REQUESTING PROOF FROM {req.connection_id} ---")

    # 1. Request the exact attributes from the Student ID schema
    # The 'restrictions' block ensures they can't submit a fake credential from a different issuer.
    requested_attributes = {
        "0_student_name_uuid": {"name": "student_name", "restrictions": [{"cred_def_id": STUDENT_CRED_DEF_ID}]},
        "1_student_id_uuid": {"name": "student_id", "restrictions": [{"cred_def_id": STUDENT_CRED_DEF_ID}]},
        "2_department_uuid": {"name": "department", "restrictions": [{"cred_def_id": STUDENT_CRED_DEF_ID}]},
        "3_email_uuid": {"name": "email", "restrictions": [{"cred_def_id": STUDENT_CRED_DEF_ID}]}
    }

    # 2. Construct Proof Request
    proof_request = {
        "name": "BRACU Student ID Verification",
        "version": "1.0",
        "requested_attributes": requested_attributes,
        "requested_predicates": {}
    }

    async with httpx.AsyncClient() as client:
        try:
            res = await client.post(
                f"{ACAPY_ADMIN_URL}/present-proof-2.0/send-request",
                json={
                    "connection_id": req.connection_id,
                    "presentation_request": {"indy": proof_request}
                }
            )
            
            if res.status_code != 200:
                print(f"❌ ACA-Py Error: {res.text}")
                raise HTTPException(status_code=500, detail="Failed to send proof request")

            pres_ex_id = res.json()["pres_ex_id"]
            print(f"✅ Proof Request Sent! Exchange ID: {pres_ex_id}")
            
            return {
                "status": "sent",
                "presentation_exchange_id": pres_ex_id,
                "message": "Verification request sent to phone."
            }
        except Exception as e:
            print(f"❌ PROOF REQUEST FAILED: {e}")
            raise HTTPException(status_code=500, detail=str(e))
          
          
@app.get("/protocol2/check-proof/{pres_ex_id}")
async def check_proof(pres_ex_id: str):
    """Polls the proof status and extracts verified attributes if successful."""
    async with httpx.AsyncClient() as client:
        try:
            res = await client.get(f"{ACAPY_ADMIN_URL}/present-proof-2.0/records/{pres_ex_id}")
            if res.status_code != 200:
                raise HTTPException(status_code=500, detail="Failed to fetch proof record")
            
            data = res.json()
            state = data.get("state")
            
            # If the proof is fully verified
            if state == "done":
                # Deep extraction of the revealed attributes from ACA-Py's JSON structure
                revealed_attrs = (
                    data.get("by_format", {})
                    .get("pres", {})
                    .get("indy", {})
                    .get("requested_proof", {})
                    .get("revealed_attrs", {})
                )
                
                # Map the raw data back to clean keys based on our request
                user_data = {
                    "student_name": revealed_attrs.get("0_student_name_uuid", {}).get("raw", "Unknown"),
                    "student_id": revealed_attrs.get("1_student_id_uuid", {}).get("raw", "Unknown"),
                    "department": revealed_attrs.get("2_department_uuid", {}).get("raw", "Unknown"), # <-- Add this
                    "email": revealed_attrs.get("3_email_uuid", {}).get("raw", "Unknown"),
                }
                
                return {"state": state, "verified": True, "user_data": user_data}
                
            return {"state": state, "verified": False}
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
          
          
          
# @app.post("/protocol2/request-lab-proof")
# async def request_lab_proof(req: VerifyRequest):
#     """Requests ONLY the department attribute to demonstrate Selective Disclosure."""
#     print(f"\n--- 🕵️ ZKP REQUEST: CSE LAB ACCESS ---")

#     # We ONLY ask for the department. Name, ID, and Email remain cryptographically hidden.
#     requested_attributes = {
#         "0_department_uuid": {
#             "name": "department", 
#             "restrictions": [{"cred_def_id": STUDENT_CRED_DEF_ID}]
#         }
#     }

#     proof_request = {
#         "name": "Anonymous Lab Access",
#         "version": "1.0",
#         "requested_attributes": requested_attributes,
#         "requested_predicates": {} # We could use this for things like 'age > 18'
#     }

#     async with httpx.AsyncClient() as client:
#         try:
#             res = await client.post(
#                 f"{ACAPY_ADMIN_URL}/present-proof-2.0/send-request",
#                 json={
#                     "connection_id": req.connection_id,
#                     "presentation_request": {"indy": proof_request}
#                 }
#             )
#             res.raise_for_status()
#             return {
#                 "status": "sent",
#                 "presentation_exchange_id": res.json()["pres_ex_id"]
#             }
#         except Exception as e:
#             raise HTTPException(status_code=500, detail=str(e))

# @app.get("/protocol2/check-lab-proof/{pres_ex_id}")
# async def check_lab_proof(pres_ex_id: str):
    """Checks the proof and enforces the CSE department requirement."""
    async with httpx.AsyncClient() as client:
        try:
            res = await client.get(f"{ACAPY_ADMIN_URL}/present-proof-2.0/records/{pres_ex_id}")
            data = res.json()
            
            if data.get("state") == "done":
                revealed_attrs = (
                    data.get("by_format", {})
                    .get("pres", {})
                    .get("indy", {})
                    .get("requested_proof", {})
                    .get("revealed_attrs", {})
                )
                
                department = revealed_attrs.get("0_department_uuid", {}).get("raw", "").upper()
                
                # Gatekeeper logic: Only CSE gets in
                if "CSE" in department or "COMPUTER SCIENCE" in department:
                    return {"state": "done", "verified": True, "department": department}
                else:
                    return {"state": "done", "verified": False, "error": "Access Denied: CSE Department Only."}
                    
            return {"state": data.get("state"), "verified": False}
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))