from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import httpx
from pydantic import BaseModel
import sqlite3

# --- SETUP UNIVERSITY DATABASE (STRICTLY ISSUER ONLY) ---
# This creates a local file named 'university.db' inside the issuer_backend folder
db_conn = sqlite3.connect('university.db', check_same_thread=False)
cursor = db_conn.cursor()

# Create a table where student_id is the UNIQUE PRIMARY KEY
#cursor.execute('DROP TABLE IF EXISTS issued_credentials')
cursor.execute('''
    CREATE TABLE IF NOT EXISTS issued_credentials (
        student_id TEXT PRIMARY KEY,
        student_name TEXT
    )
''')
db_conn.commit()

# --- CONFIGURATION ---
# Talks ONLY to the Issuer ACA-Py Agent
ACAPY_ADMIN_URL = "http://127.0.0.1:8020"

# Schema & Credential Definition IDs generated by setup_schemas.py
STUDENT_SCHEMA_ID = "GEX6Tv3ywc7HzWukCyveY5:2:student_id_credential:1.9360"
STUDENT_CRED_DEF_ID = "GEX6Tv3ywc7HzWukCyveY5:3:CL:3225281:brac_tag_9360"
# --- PYDANTIC REQUEST MODELS ---
class RegisterRequest(BaseModel):
    gov_id: str
    name: str

class IssueCredentialRequest(BaseModel):
    connection_id: str
    student_name: str
    student_id: str
    department: str
    email: str

# --- APPLICATION SETUP ---
app = FastAPI(
    title="BRACU Issuer Backend (Registrar)",
    description="Handles identity registration and decentralized credential issuance.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows all origins for local testing
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- ROUTES ---

@app.get("/")
def health_check():
    """Basic health check endpoint to confirm Issuer backend availability."""
    return {
        "status": "active",
        "role": "Issuer (Registrar)",
        "acapy_url": ACAPY_ADMIN_URL,
    }

@app.post("/protocol1/create-invitation")
async def create_invitation():
    """Generates a QR code invitation for the mobile wallet to scan."""
    async with httpx.AsyncClient() as client:
        try:
            res = await client.post(
                f"{ACAPY_ADMIN_URL}/connections/create-invitation",
                params={"auto_accept": "true"}
            )
            res.raise_for_status()
            data = res.json()
            
            return {
                "status": "success",
                "connection_id": data["connection_id"],
                "invitation_url": data["invitation_url"]
            }
        except Exception as e:
            print(f"❌ Failed to create invitation: {e}")
            raise HTTPException(status_code=500, detail="Failed to create connection invitation")
          
@app.post("/protocol1/register")
async def create_ssi_identity(req: RegisterRequest):
    """Generates a new Ed25519 DID inside the ACA-Py wallet for local user registration."""
    print(f"\n--- 🆔 PROTOCOL 1: GENERATING SSI IDENTITY FOR {req.name.upper()} ---")

    async with httpx.AsyncClient() as client:
        # 1. Verify ACA-Py Agent Availability
        try:
            health = await client.get(f"{ACAPY_ADMIN_URL}/status/ready")
            health.raise_for_status()
        except Exception:
            raise HTTPException(
                status_code=502,
                detail="ACA-Py Agent is unreachable. Check Docker container status.",
            )

        # 2. Create Ed25519 DID via ACA-Py
        try:
            response = await client.post(
                f"{ACAPY_ADMIN_URL}/wallet/did/create",
                json={"method": "sov", "options": {"key_type": "ed25519"}},
            )
            response.raise_for_status()

            data = response.json()["result"]
            ssi_did = data["did"]
            verkey = data["verkey"]

            print(f"   ↳ 🔐 Keypair Generated | DID: {ssi_did}")

            return {
                "status": "success",
                "ssi_did": ssi_did,
                "verkey": verkey,
                "gov_id": req.gov_id,
                "message": "Identity keypair successfully provisioned in wallet.",
            }

        except Exception as e:
            print(f"❌ DID Creation Failed: {e}")
            raise HTTPException(
                status_code=500, detail=f"Failed to generate DID: {str(e)}"
            )

@app.get("/protocol1/check-connection/{connection_id}")
async def check_connection(connection_id: str):
    """Polling endpoint used by frontend to verify if student has scanned the QR code."""
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(
                f"{ACAPY_ADMIN_URL}/connections/{connection_id}"
            )
            if response.status_code == 404:
                raise HTTPException(status_code=404, detail="Connection ID not found")

            response.raise_for_status()
            data = response.json()
            state = data.get("state", "unknown")
            is_connected = state in ["active", "response"]

            return {
                "connection_id": connection_id,
                "state": state,
                "connected": is_connected,
            }

        except HTTPException:
            raise
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
    
@app.post("/protocol1/issue-credential")
async def issue_credential(req: IssueCredentialRequest):
    """Issues a Student ID credential directly to the connected mobile wallet."""
    print(f"\n--- 🚀 ISSUING STUDENT ID TO CONNECTION: {req.connection_id} ---")
    
    try:
        # 🚨 THE GATEKEEPER CHECK (Database access restricted to Issuer!) 🚨
        # 1. Check if this Student ID has already been issued
        cursor.execute("SELECT student_name FROM issued_credentials WHERE student_id = ?", (req.student_id,))
        existing_record = cursor.fetchone()
        
        if existing_record:
            print(f"⚠️ REJECTED: Credential already exists for ID {req.student_id}")
            raise HTTPException(
                status_code=400, 
                detail=f"A credential for Student ID {req.student_id} has already been issued."
            )

        # 2. Map the attributes
        aca_py_attributes = [
            {"name": "student_name", "value": req.student_name},
            {"name": "student_id", "value": req.student_id},
            {"name": "department", "value": req.department},
            {"name": "email", "value": req.email}
        ]

        # 3. Send the Credential Offer via ACA-Py
        async with httpx.AsyncClient() as client:
            aca_res = await client.post(
                f"{ACAPY_ADMIN_URL}/issue-credential-2.0/send",
                json={
                    "connection_id": req.connection_id,
                    "filter": {
                        "indy": {
                            "cred_def_id": STUDENT_CRED_DEF_ID,
                            "schema_id": STUDENT_SCHEMA_ID
                        }
                    },
                    "credential_preview": {
                        "@type": "issue-credential/2.0/credential-preview",
                        "attributes": aca_py_attributes
                    }
                },
                timeout=30.0
            )
            
            if aca_res.status_code != 200:
                raise HTTPException(status_code=aca_res.status_code, detail=f"ACA-Py error: {aca_res.text}")

            data = aca_res.json()
            exchange_id = data.get("cred_ex_id")
            
            # 🚨 SECURE THE ID 🚨
            # 4. Save the issued ID to the database so it can't be registered again
            cursor.execute(
                "INSERT INTO issued_credentials (student_id, student_name) VALUES (?, ?)",
                (req.student_id, "XXXXX")
            )
            db_conn.commit()

            print(f"✅ Credential Offer Sent! ID {req.student_id} is now locked in the database.")

            return {
                "status": "success",
                "message": "Student ID Credential sent to mobile wallet.",
                "exchange_id": exchange_id
            }

    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ ISSUANCE FAILED: {e}")
        raise HTTPException(status_code=500, detail=str(e))